#ifndef MOUSE_BUTTON_CODES_HDR
#define MOUSE_BUTTON_CODES_HDR

//From GLFW3.h
#define TEMP_MOUSE_BUTTON_1         0
#define TEMP_MOUSE_BUTTON_2         1
#define TEMP_MOUSE_BUTTON_3         2
#define TEMP_MOUSE_BUTTON_4         3
#define TEMP_MOUSE_BUTTON_5         4
#define TEMP_MOUSE_BUTTON_6         5
#define TEMP_MOUSE_BUTTON_7         6
#define TEMP_MOUSE_BUTTON_8         7
#define TEMP_MOUSE_BUTTON_LAST      TEMP_MOUSE_BUTTON_8
#define TEMP_MOUSE_BUTTON_LEFT      TEMP_MOUSE_BUTTON_1
#define TEMP_MOUSE_BUTTON_RIGHT     TEMP_MOUSE_BUTTON_2
#define TEMP_MOUSE_BUTTON_MIDDLE    TEMP_MOUSE_BUTTON_3

#endif // !MOUSE_BUTTON_CODES_HDR
